--- 
- name: "Test IOS command."
  hosts: all
  gather_facts: true
    
  tasks:
  - name: "show ip interface brief"
    ios_command: 
      commands:
        - show ip int brief
    register: result
    
  - name: show debud
      debug: 
      - var: result.stdout
