--- 
- name: "Test IOS command."
  hosts: all
  gather_facts: true
    
  tasks:
  - name: "show ip interface brief"
    ios_command: 
      commands:
        - show ip int brief
        - show version
    register: result
  - debug: msg="{{result.stdout}}"
