--- 
- name: "Test IOS command."
  hosts: all
  gather_facts: true
  connection: network_cli
  
  tasks:
  - name: "show ip interface brief"
    ios_command: 
      lines:
        - "show ip int brief"
